# Generated by Django 3.2.21 on 2023-10-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='key_pair_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
