# Generated by Django 3.2.21 on 2023-10-14 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_machine_key_pair_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('sg_id', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='machine',
            name='blog',
        ),
        migrations.AddField(
            model_name='machine',
            name='instance_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='MachineBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.blog')),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.machine')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='security_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.securitygroup'),
        ),
    ]
