# Generated by Django 3.2.21 on 2023-10-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20231014_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='policy_agreement',
        ),
    ]
